### ISSUE TITLE
gateway command

### ISSUE THREAD

**Issue by chipv-crystal** [michaelbironneau/gateway#1]
Hi @michaelbironneau 

thanks for sharing. please help me to under stand command: gateway

which package need to be install to run gateway command?

thanks

**Comment by michaelbironneau** [comment]
1. Install Go according to the [official instructions for your platform](https://golang.org/doc/install), including setting up your gopath
2. Run `go get github.com/michaelbironneau/gateway`
3. Go to `$GOPATH/src/github.com/michaelbironneau/gateway` and run `go install` there.

Gateway has no dependencies outside the Go standard library, as you can see [here](https://godoc.org/github.com/michaelbironneau/gateway/lib?imports).
